# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    name: Smoke (no creds)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run smoke suite
        run: mvn -B -Dheadless=true -Dgroups=smoke clean test
      - name: Upload reports (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-smoke
          path: |
            target/surefire-reports/**
            target/screenshots/**

  full:
    name: Full (with creds)
    runs-on: ubuntu-latest
    env:
      # expose secrets as env so we can reference them without hitting the parser error
      VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Skip if creds not set
        if: ${{ env.VALID_EMAIL == '' || env.VALID_PASSWORD == '' }}
        run: |
          echo "VALID_EMAIL or VALID_PASSWORD not set; skipping full suite."
          exit 0

      - name: Run full suite
        run: |
          mvn -B -Dheadless=true \
            -DvalidEmail="${{ env.VALID_EMAIL }}" \
            -DvalidPassword="${{ env.VALID_PASSWORD }}" \
            clean test

      - name: Upload reports (full)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-full
          path: |
            target/surefire-reports/**
            target/screenshots/**
